@myApi = http://localhost:4000

### Sign Up
POST {{myApi}}/auth/signup
Content-Type: application/json

{
  "name": "Maria",
  "email": "maria@company.com",
  "password": "testpass123456",
  "confirm_password": "testpass123456"
}

### Sign In
POST {{myApi}}/auth/signin
Content-Type: application/json

{
  "email": "admin@company.com",
  "password": "admintestpass123456"
}