@myApi = http://localhost:4000

### Sign Up
POST {{myApi}}/auth/signup

### Sign In
POST {{myApi}}/auth/signin
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "testpass123456"
}