@myApi = http://localhost:4000

### New Product
POST {{myApi}}/products/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNmUxMTA4NDUyZjRjMTZhYmI2NTk1MSIsImlhdCI6MTYzNDYwNTQ4MywiZXhwIjoxNjM0NjkxODgzfQ.WKLsl9wd0ON6w-ILRonGKg7sq_pGjlVhUU3K0OHRDxU

{
  "name": "Laptop Lenovo",
  "category": "Laptops",
  "price": 999.99,
  "imgURL": "https://infotec.com.pe/40578-large_default/laptop-lenovo-v14-iil-i5-1035g1-8gb-1tb-14-hd-freedos-82c400eelm.jpg"
}

### Get All Products
GET {{myApi}}/products/

### Get Product
GET {{myApi}}/products/616e16fcf8ca5bfa6a119a18

### Update Product
PUT {{myApi}}/products/616e16fcf8ca5bfa6a119a18
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNmUxODA2ZWVkNDRhODQzNjRmOGY2YSIsImlhdCI6MTYzNDYwNTU1MywiZXhwIjoxNjM0NjkxOTUzfQ.FsljfxX8V8rxG5bIvw4U0VKqFAz3gEczYAE0svlojGQ

{
  "name": "Laptop Lenovo Thinkpad T400",
  "price": 899.99
}

### Delete Product
DELETE {{myApi}}/products/616e16fcf8ca5bfa6a119a18
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNmUxODA2ZWVkNDRhODQzNjRmOGY2YSIsImlhdCI6MTYzNDYwNTU1MywiZXhwIjoxNjM0NjkxOTUzfQ.FsljfxX8V8rxG5bIvw4U0VKqFAz3gEczYAE0svlojGQ

