@myApi = http://localhost:3000

### New User
POST {{myApi}}/users/
Content-Type: application/json

{
  "name": "Test name",
  "email": "test@example.com",
  "password": "testpass123456",
  "confirm_password": "testpass123456"
}

### Get All Users
GET {{myApi}}/users/

### Get User
GET {{myApi}}/users/1
